[build]
  command = "npm run build"
  publish = "out"
  
[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Estas redirecciones son necesarias para el App Router de Next.js
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

